### ISSUE TITLE
Not serializable

### ISSUE THREAD

**Issue by leolux** [bolerio/mjson#19]
I integrated mjson inside a JSF web application and it requires the Json instances to be serializable:
    java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: mjson.Json$ObjectJson

The issue may be solved by adding "implements Serializable" to the objects ArrayJson, BooleanJson, NullJson, NumberJson, ObjectJson and StringJson. What do you think?

**Comment by bolerio** [comment]
Hi,

This is already changed in 1.4-SNAPSHOT, which you could actually use instead of 1.3.

**Comment by leolux** [comment]
Where to find the new version? http://repo1.maven.org/maven2/org/sharegov/mjson/ has only 1.3

**Comment by bolerio** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/sharegov/mjson/1.4-SNAPSHOT/

You should be able to add the sonatype snapshot repo to your MAven settings.xml or pom.xml so you are able to access snapshot versions of libraries.

**Comment by leolux** [comment]
Thanks!

<repository>
			<id>sonatype-nexus-snapshots</id>
			<name>Sonatype Nexus Snapshots</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
